---
title: "Compare long-read vs short-read results"
author: "Xueyi Dong"
date: '2022-07-13'
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache=TRUE)
```

## Prepare and load packages
```{r setup2}
library(edgeR)
library(limma)
library(ggplot2)
library(dplyr)
library(ggVennDiagram)
library(viridis)
library(VennDiagram)
```

## Compare DTE results

```{r DTE}
tt.long <- read.csv("results/DE_topTags.csv", row.names = 1)
tt.short <- read.csv("results_short/DE_topTags.csv", row.names = 1)
# long vs short F
F <- data.frame(
  f.long = tt.long$F,
  f.short = tt.short$F[match(rownames(tt.long), rownames(tt.short))],
  logFC.long = tt.long$logFC,
  logFC.short = tt.short$logFC[match(rownames(tt.long), rownames(tt.short))]
)
F <- na.omit(F)
plot.f <- ggplot(F, aes(x=f.long, y=f.short)) +
  stat_binhex(bins = 100) +
  scale_fill_viridis() +
  theme_bw() +
  scale_x_continuous(trans = "log10") +
  scale_y_continuous(trans = "log10") +
  theme(text = element_text(size = 20)) +
  labs(x = "ONT long-read F", y = "Illumina short-read F")
print(plot.f)

cor(F$f.long, F$f.short)

plot.logFC <- ggplot(F, aes(x=logFC.long, y=logFC.short)) +
  stat_binhex(bins = 100) +
  scale_fill_viridis() +
  theme_bw() +
  theme(text = element_text(size = 20)) +
  labs(x = "ONT long-read logFC", y = "Illumina short-read logFC")
print(plot.logFC)

cor(F$logFC.long, F$logFC.short)

# Venn diagram of significant DTEs
DTE.transcripts <- list(
  long = tt.long$qry_id[tt.long$FDR < 0.05],
  short = tt.short$qry_id[tt.short$FDR < 0.05]
)
venn.DTE <- ggVennDiagram(DTE.transcripts) +
  scale_fill_viridis()
print(venn.DTE)

venn.diagram(
  DTE.transcripts,
  category.names = c("ONT", "Illumina"),
  main = "Significant DTEs",
  filename = "plots/compare/DTEvenn.tiff",
  output = TRUE,
  height = 1500,
  width = 2400,
  fill = c("#438DAC", "#FCB344"),
  fontfamily = "Arial",
  main.fontfamily = "Arial",
  sub.fontfamily = "Arial",
  cat.fontfamily = "Arial",
  cat.pos = c(-30, 30)
)

# Check overlapped DTE transcripts
DTE.intersect <- data.frame(
  transcript = intersect(DTE.transcripts$long, DTE.transcripts$short)
)
DTE.intersect$gene <- tt.long$qry_gene_id[match(DTE.intersect$transcript, tt.long$qry_id)]
DTE.intersect$logFC.long <- tt.long[DTE.intersect$transcript, "logFC"]
DTE.intersect$logFC.short <- tt.short[DTE.intersect$transcript, "logFC"]
DTE.intersect
# check direction
table(DTE.intersect$logFC.long > 0, DTE.intersect$logFC.short > 0)
# Venn diagram of top 1000 DTEs
DTE.top1000 <-list(
  long = tt.long$qry_id[1:1000],
  short = tt.short$qry_id[1:1000]
)
venn.DTEtop1000 <- ggVennDiagram(DTE.top1000) +
  scale_fill_viridis()
print(venn.DTEtop1000)

venn.diagram(
  DTE.top1000,
  category.names = c("ONT", "Illumina"),
  main = "Top 1000 DTEs",
  filename = "plots/compare/DTEvennTop1000.tiff",
  output = TRUE,
  height = 1500,
  width = 2400,
  fill = c("#438DAC", "#FCB344"),
  fontfamily = "Arial",
  main.fontfamily = "Arial",
  sub.fontfamily = "Arial",
  cat.fontfamily = "Arial",
  cat.pos = c(-25, 25)
)

# Gene set testing and barcode plots, short tx in long data
lcpm.long <- readRDS("rds/lcpm.long.RDS")
group <- rep(c("control", "targeted"), c(4, 4))
design <- model.matrix(~group)
index <- data.frame(Gene = tt.short$qry_id[tt.short$FDR < 0.05],
                    Weight = tt.short$logFC[tt.short$FDR < 0.05])
index <- index[!is.na(match(index$Gene, tt.long$qry_id)),]
test.res <- fry(lcpm.long, index, design)
barcodeplot(tt.long$logFC, index=match(index$Gene, tt.long$qry_id), gene.weights = index$Weight,
            main = paste("Short-read DTEs in long-read data\nfry", test.res$Direction, "P-value =", signif(test.res$PValue, 3)))

# Gene set testing and barcode plots, long tx in short data
lcpm.short <- readRDS("rds/lcpm.short.RDS")
index <- data.frame(Gene = tt.long$qry_id[tt.long$FDR < 0.05],
                    Weight = tt.long$logFC[tt.long$FDR < 0.05])
index <- index[!is.na(match(index$Gene, tt.short$qry_id)),]
test.res <- fry(lcpm.short, index, design)
barcodeplot(tt.short$logFC, index=match(index$Gene, tt.short$qry_id), gene.weights = index$Weight,
            main = paste("Long-read DTEs in short-read data\nfry", test.res$Direction, "P-value =", signif(test.res$PValue, 3)))
```

### Save plots as PDF files

```{r DTEpdf}
pdf("plots/compare/F.pdf", height = 5, width = 8)
print(plot.f)
dev.off()

pdf("plots/compare/logFC.pdf", height  = 5, width = 8)
print(plot.logFC)
dev.off()

pdf("plots/compare/DTEvenn.pdf", height = 5, width = 8)
print(venn.DTE)
dev.off()

pdf("plots/compare/DTEvennTop1000.pdf", height = 5, width = 8)
print(venn.DTEtop1000)
dev.off()

pdf("plots/compare/DTEbarcode.pdf", height = 5, width = 8)
index <- data.frame(Gene = tt.short$qry_id[tt.short$FDR < 0.05],
                    Weight = tt.short$logFC[tt.short$FDR < 0.05])
index <- index[!is.na(match(index$Gene, tt.long$qry_id)),]
test.res <- fry(lcpm.long, index, design)
barcodeplot(tt.long$logFC, index=match(index$Gene, tt.long$qry_id), gene.weights = index$Weight,
            cex.lab = 1.5,
            cex.main = 1.5,
            cex = 2,
            xlab = "log fold change",
            main = paste("Short-read DTEs in long-read data\nfry", test.res$Direction, "P-value =", signif(test.res$PValue, 3)))
index <- data.frame(Gene = tt.long$qry_id[tt.long$FDR < 0.05],
                    Weight = tt.long$logFC[tt.long$FDR < 0.05])
index <- index[!is.na(match(index$Gene, tt.short$qry_id)),]
test.res <- fry(lcpm.short, index, design)
barcodeplot(tt.short$logFC, index=match(index$Gene, tt.short$qry_id), gene.weights = index$Weight,
            cex.lab = 1.5,
            cex.main = 1.5,
            cex = 2,
            xlab = "log fold change",
            main = paste("Long-read DTEs in short-read data\nfry", test.res$Direction, "P-value =", signif(test.res$PValue, 3)))
dev.off()
```


## Compare DTU results

### Gene-level results

```{r DTUgene}
ts.long <- read.csv("results/DTU_gene_topSplice.csv", row.names = 1)
ts.short <- read.csv("results_short/DTU_gene_topSplice.csv", row.names = 1)
# Venn diagram of significant DTU gene
DTU.genes <- list(
  long = ts.long$qry_gene_id[ts.long$FDR < 0.05],
  short = ts.short$qry_gene_id[ts.short$FDR < 0.05]
)
ggVennDiagram(DTU.genes) +
  scale_fill_viridis()

venn.diagram(
  DTU.genes,
  category.names = c("ONT", "Illumina"),
  main = "Significant gene-level DTUs",
  filename = "plots/compare/DTUvennGene.tiff",
  output = TRUE,
  height = 1500,
  width = 2400,
  fill = c("#438DAC", "#FCB344"),
  fontfamily = "Arial",
  main.fontfamily = "Arial",
  sub.fontfamily = "Arial",
  cat.fontfamily = "Arial",
  cat.pos = c(-150, 150)
)
```

### Transcript-level results

```{r DTUtx}
ts.tx.long <- read.csv("results/DTU_transcript_topSplice.csv", row.names = 1)
ts.tx.short <- read.csv("results_short/DTU_transcript_topSplice.csv", row.names = 1)
DTU.transcripts <- list(
  long = ts.tx.long$qry_id[ts.tx.long$FDR < 0.05],
  short = ts.tx.short$qry_id[ts.tx.short$FDR < 0.05]
)
# venn diagram
ggVennDiagram(DTU.transcripts) +
  scale_fill_viridis()

venn.diagram(
  DTU.transcripts,
  category.names = c("ONT", "Illumina"),
  main = "Significant transcript-level DTUs",
  filename = "plots/compare/DTUvennTx.tiff",
  output = TRUE,
  height = 1500,
  width = 2400,
  fill = c("#438DAC", "#FCB344"),
  fontfamily = "Arial",
  main.fontfamily = "Arial",
  sub.fontfamily = "Arial",
  cat.fontfamily = "Arial",
  cat.pos = c(-150, 150)
)
# Check overlapped DTU transcripts
DTU.intersect <- data.frame(
  transcript = intersect(DTU.transcripts$long, DTU.transcripts$short)
)
DTU.intersect$gene <- ts.tx.long$qry_gene_id[match(DTU.intersect$transcript, ts.tx.long$qry_id)]
DTU.intersect$logFC.long <- ts.tx.long[match(DTU.intersect$transcript, ts.tx.long$qry_id), "logFC"]
DTU.intersect$logFC.short <- ts.tx.short[match(DTU.intersect$transcript, ts.tx.short$qry_id), "logFC"]
DTU.intersect
# check direction
table(DTU.intersect$logFC.long > 0, DTU.intersect$logFC.short > 0)
# barcode plot, short tx in long data
barcodeplot(ts.tx.long$logFC, index = na.omit(match(DTU.transcripts$short, ts.tx.long$qry_id)), 
            gene.weights = ts.tx.short$logFC[match(DTU.transcripts$short[DTU.transcripts$short %in% ts.tx.long$qry_id], ts.tx.short$qry_id)],
            main = "Short-read DTU transcripts in long-read data")
# barcode plot, long tx in short data
barcodeplot(ts.tx.short$logFC, index = na.omit(match(DTU.transcripts$long, ts.tx.short$qry_id)), 
            gene.weights = ts.tx.long$logFC[match(DTU.transcripts$long[DTU.transcripts$long %in% ts.tx.short$qry_id], ts.tx.long$qry_id)],
            main = "Long-read DTU transcripts in short-read data")
```

### Save plots as PDF files

```{r DTUpdf}
pdf("plots/compare/DTUbarcode.pdf", height = 5, width = 8)
# barcode plot, short tx in long data
barcodeplot(ts.tx.long$t, index = na.omit(match(DTU.transcripts$short, ts.tx.long$qry_id)), 
            gene.weights = ts.tx.short$logFC[match(DTU.transcripts$short[DTU.transcripts$short %in% ts.tx.long$qry_id], ts.tx.short$qry_id)],
            cex.lab = 1.5,
            cex.main = 1.5,
            cex = 2,
            xlab = "t-statistic",
            main = "Short-read DTU transcripts in long-read data")
# barcode plot, long tx in short data
barcodeplot(ts.tx.short$t, index = na.omit(match(DTU.transcripts$long, ts.tx.short$qry_id)), 
            gene.weights = ts.tx.long$logFC[match(DTU.transcripts$long[DTU.transcripts$long %in% ts.tx.short$qry_id], ts.tx.long$qry_id)],
            cex.lab = 1.5,
            cex.main = 1.5,
            cex = 2,
            xlab = "t-statistic",
            main = "Long-read DTU transcripts in short-read data")
dev.off()

t <- data.frame(
  t.long = ts.tx.long$t,
  t.short = ts.tx.short$t[match(ts.tx.long$qry_id, ts.tx.short$qry_id)]
)
t <- na.omit(t)
cor(t$t.long, t$t.short)
pdf("plots/compare/DTUt.pdf", height = 5, width = 8)
ggplot(t, aes(x=t.long, y=t.short)) +
  stat_binhex(bins = 100) +
  scale_fill_viridis() +
  theme_bw() +
  scale_x_continuous(trans = "log10") +
  scale_y_continuous(trans = "log10") +
  theme(text = element_text(size = 20)) +
  labs(x = "ONT long-read t", y = "Illumina short-read t")
dev.off()
```


## Session information
```{r sessionInfo}
sessionInfo()
```

